# Generated by Django 6.0.3 on 2026-03-05 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='file_links',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='token',
            name='task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='token',
            name='task_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=20, null=True),
        ),
    ]
